@url = http://127.0.0.1:3000
@json = Content-Type: application/json

POST {{url}}/a
{{json}}

{
  "a": "hello"
}

###

GET {{url}}/hello

###

TRACE {{url}}/hello

###
POST {{url}}/hello
{{json}}

{
  "a": "hello"
}

###

OPTIONS {{url}}/hello

###  

GET {{url}}/news